version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      APP_ADDR: :8080
      NS_MARIADB_USER: root
      NS_MARIADB_PASS: pass
      NS_MARIADB_HOSTNAME: db
      NS_MARIADB_PORT: "3306"
      NS_MARIADB_NAME: app
      NS_MARIADB_DATABASE: db
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./

  db:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
    expose:
      - "3306"
    healthcheck:
      test: mysql --user=root --password=pass --execute "SHOW DATABASES;"
      interval: 1s
      timeout: 10s
      retries: 30

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
